default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: leedslocal_development
test:
  <<: *default
  database: leedslocal_test
production:
  <<: *default
  database: leedslocal_production
